### ISSUE TITLE
HappyPack does not notices the cache?

### ISSUE THREAD

**Issue by XVincentX** [amireh/happypack#13]
I am not sure why, but when using `webpack-dev-server`, happypack is writing `.happypack` directory but on the same time, it is not able to detect the cache and regenerates the entire build on subsequent runs.

Any suggestion?

**Comment by amireh** [comment]
Hmmm, that's strange. I personally don't use the devserver but I'll take a look.

**Comment by XVincentX** [comment]
Looks like it does not work even if using the command line tool:

`./node_modules/.bin/webpack --config Webpackfile.js`

leads to:

![image](https://cloud.githubusercontent.com/assets/1416224/12266607/56cd7cc0-b944-11e5-9b62-77c6ba948395.png)

Every time.

**Comment by amireh** [comment]
Hmm, curious. What does the `.happypack/` folder contain? Is there a `cache--[something].json` file?

**Comment by XVincentX** [comment]
Yes, I have one file per loader id

**Comment by amireh** [comment]
Size of the file? Is it possible to paste the contents of it somewhere?

**Comment by XVincentX** [comment]
```bash
$ ls -la | grep cache

-rw-r--r--    1 vchianese  staff  66262 Jan 13 14:56 cache--coffee.json
-rw-r--r--    1 vchianese  staff  21430 Jan 13 14:56 cache--ect.json
```

I'll try to do something to post its content.

**Comment by amireh** [comment]
Thanks. The relevant bit in the cache contents will be an object with the key `context`; this controls whether the cache contents are valid or not between different runs.

**Comment by XVincentX** [comment]
The context object itself is empty

```json
{"context":{},"mtimes":...
```

And then I have a `mtimes` object with `path: mtime {}`

**Comment by XVincentX** [comment]
@amireh Is that enough or - would you still want to have a look at files?

**Comment by amireh** [comment]
I know that the context should not be empty, at the very least it should contain a "loaders" attribute. I will take a look tonight if possible.

No need for the rest of the file contents, this is enough :) thanks

Which OS do you use btw? Is this on node 0.10 ?

**Comment by XVincentX** [comment]
```bash
$ uname -a
Darwin Vincenzos-MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
$ node -v
v0.10.37
$ npm -v
2.14.14
```

**Comment by amireh** [comment]
Ok, because the other similar report I got was also from OS X, but using node 0.12. Thanks, will update when I find something.

**Comment by amireh** [comment]
@XVincentX I just pushed 1.1.3 with a possible fix, please confirm when you can test it!

**Comment by XVincentX** [comment]
@amireh 
So, now the context key is populated, but I am still getting no cache:

```json
{
  "context": {
    "loaders": [
      {
        "path": "/somePath/lib/webpack/ect-loader.js"
      }
    ],
    "external": {}
  }
}
```

This is the second run:
```bash
$ ./node_modules/.bin/webpack --config Webpackfile.js
Happy[coffee]: Firing up! Version: 1.1.3. Using cache? yes. Threads: 3
Happy[coffee]: No cache was found, starting fresh.
Happy[coffee]: All set; signalling webpack to proceed.
Happy[ect]: Firing up! Version: 1.1.3. Using cache? yes. Threads: 3
Happy[ect]: No cache was found, starting fresh.
Happy[ect]: All set; signalling webpack to proceed.
```

**Comment by amireh** [comment]
So the examples seem to work if I run them using:

```shell
./node_modules/.bin/webpack-dev-server --config examples/single-loader/webpack.config.js
```

And they seem to be picking up the cache. Is there a special way you're running the devserver? Can i see the webpack config file please?

**Comment by amireh** [comment]
Can you verify whether this was fixed in 1.1.4 (see #17 for more information)?

**Comment by XVincentX** [comment]
This looks great. I'll let you know

**Comment by XVincentX** [comment]
@amireh Unfortunately no. I'll make other tests but at first glance it seems still broken.

**Comment by XVincentX** [comment]
@amireh 

Ok I was tired of this problem and decided to investigate. Basically node 0.10 does not have `fs.accessSync`, but `bs.existsSync`.

Would that be possible to create a fallback for that?
